/** A record with fully qualified type name as index. 
 * The value is an array with index 0 representing the keyword to replace and index 1 the new keyword */
export const apiNameMap: Record<string, [string, string]> = {
	// AptClient
	"GreyHack.AptClient.addRepo": ["addRepo", "add_repo"],
	"GreyHack.AptClient.checkUpgrade": ["checkUpgrade", "check_upgrade"],
	"GreyHack.AptClient.delRepo": ["delRepo", "del_repo"],
	// Blockchain
	"GreyHack.Blockchain.amountMined": ["amountMined", "amount_mined"],
	"GreyHack.Blockchain.coinPrice": ["coinPrice", "coin_price"],
	"GreyHack.Blockchain.createWallet": ["createWallet", "create_wallet"],
	"GreyHack.Blockchain.deleteCoin": ["deleteCoin", "delete_coin"],
	"GreyHack.Blockchain.getCoin": ["getCoin", "get_coin"],
	"GreyHack.Blockchain.getCoinName": ["getCoinName", "get_coin_name"],
	"GreyHack.Blockchain.loginWallet": ["loginWallet", "login_wallet"],
	"GreyHack.Blockchain.showHistory": ["showHistory", "show_history"],
	// Coin
	"GreyHack.Coin.createSubwallet": ["createSubwallet", "create_subwallet"],
	"GreyHack.Coin.getAddress": ["getAddress", "get_address"],
	"GreyHack.Coin.getCycleMining": ["getCycleMining", "get_cycle_mining"],
	"GreyHack.Coin.getMinedCoins": ["getMinedCoins", "get_mined_coins"],
	"GreyHack.Coin.getReward": ["getReward", "get_reward"],
	"GreyHack.Coin.getSubwallet": ["getSubwallet", "get_subwallet"],
	"GreyHack.Coin.getSubwallets": ["getSubwallets", "get_subwallets"],
	"GreyHack.Coin.resetPassword": ["resetPassword", "reset_password"],
	"GreyHack.Coin.setAddress": ["setAddress", "set_address"],
	"GreyHack.Coin.setCycleMining": ["setCycleMining", "set_cycle_mining"],
	"GreyHack.Coin.setReward": ["setReward", "set_reward"],
	// Computer
	"GreyHack.BaseComputer.file": ["file", "File"],
	"GreyHack.Computer.activeNetCard": ["activeNetCard", "active_net_card"],
	"GreyHack.Computer.changePassword": ["changePassword", "change_password"],
	"GreyHack.Computer.closeProgram": ["closeProgram", "close_program"],
	"GreyHack.Computer.connectEthernet": ["connectEthernet", "connect_ethernet"],
	"GreyHack.Computer.connectWifi": ["connectWifi", "connect_wifi"],
	"GreyHack.BaseComputer.createFolder": ["createFolder", "create_folder"],
	"GreyHack.Computer.createGroup": ["createGroup", "create_group"],
	"GreyHack.Computer.createUser": ["createUser", "create_user"],
	"GreyHack.Computer.deleteGroup": ["deleteGroup", "delete_group"],
	"GreyHack.Computer.deleteUser": ["deleteUser", "delete_user"],
	"GreyHack.BaseComputer.getName": ["getName", "get_name"],
	"GreyHack.Computer.getPorts": ["getPorts", "get_ports"],
	"GreyHack.Computer.isNetworkActive": ["isNetworkActive", "is_network_active"],
	"GreyHack.Computer.localIp": ["localIp", "local_ip"],
	"GreyHack.Computer.networkDevices": ["networkDevices", "network_devices"],
	"GreyHack.Computer.networkGateway": ["networkGateway", "network_gateway"],
	"GreyHack.Computer.publicIp": ["publicIp", "public_ip"],
	"GreyHack.Computer.showProcs": ["showProcs", "show_procs"],
	"GreyHack.Computer.wifiNetworks": ["wifiNetworks", "wifi_networks"],
	// Crypto
	"GreyHack.Crypto.isEncrypted": ["isEncrypted", "is_encrypted"],
	"GreyHack.Crypto.smtpUserList": ["smtpUserList", "smtp_user_list"],
	// Ctfevent
	"GreyHack.Ctfevent.getCreatorName": ["getCreatorName", "get_creator_name"],
	"GreyHack.Ctfevent.getDescription": ["getDescription", "get_description"],
	"GreyHack.Ctfevent.getMailContent": ["getMailContent", "get_mail_content"],
	"GreyHack.Ctfevent.getTemplate": ["getTemplate", "get_template"],
	"GreyHack.Ctfevent.playerSuccess": ["playerSuccess", "player_success"],
	// DebugLibrary
	"GreyHack.DebugLibrary.applyPatch": ["applyPatch", "apply_patch"],
	"GreyHack.DebugLibrary.unitTesting": ["unitTesting", "unit_testing"],
	// File
	"GreyHack.File.allowImport": ["allowImport", "allow_import"],
	"GreyHack.File.getContent": ["getContent", "get_content"],
	"GreyHack.File.getFiles": ["getFiles", "get_files"],
	"GreyHack.File.getFolders": ["getFolders", "get_folders"],
	"GreyHack.FtpFile.getFiles": ["getFiles", "get_files"],
	"GreyHack.FtpFile.getFolders": ["getFolders", "get_folders"],
	"GreyHack.BaseFile.hasPermission": ["hasPermission", "has_permission"],
	"GreyHack.BaseFile.isBinary": ["isBinary", "is_binary"],
	"GreyHack.BaseFile.isFolder": ["isFolder", "is_folder"],
	"GreyHack.BaseFile.isSymlink": ["isSymlink", "is_symlink"],
	"GreyHack.File.setContent": ["setContent", "set_content"],
	"GreyHack.File.setGroup": ["setGroup", "set_group"],
	"GreyHack.File.setOwner": ["setOwner", "set_owner"],
	// General
	"GreyHack.activeUser": ["activeUser", "active_user"],
	"GreyHack.clearScreen": ["clearScreen", "clear_screen"],
	"GreyHack.commandInfo": ["commandInfo", "command_info"],
	"GreyHack.currentDate": ["currentDate", "current_date"],
	"GreyHack.currentPath": ["currentPath", "current_path"],
	"GreyHack.formatColumns": ["formatColumns", "format_columns"],
	"GreyHack.getAbsPath": ["getAbsPath", "get_abs_path"],
	"GreyHack.getCtf": ["getCtf", "get_ctf"],
	"GreyHack.getCustomObject": ["getCustomObject", "get_custom_object"],
	"GreyHack.getRouter": ["getRouter", "get_router"],
	"GreyHack.getShell": ["getShell", "get_shell"],
	"GreyHack.getSwitch": ["getSwitch", "get_switch"],
	"GreyHack.homeDir": ["homeDir", "home_dir"],
	"GreyHack.importCode": ["importCode", "import_code"],
	"GreyHack.includeLib": ["includeLib", "include_lib"],
	"GreyHack.isLanIp": ["isLanIp", "is_lan_ip"],
	"GreyHack.isValidIp": ["isValidIp", "is_valid_ip"],
	"GreyHack.launchPath": ["launchPath", "launch_path"],
	"GreyHack.mailLogin": ["mailLogin", "mail_login"],
	"GreyHack.parentPath": ["parentPath", "parent_path"],
	"GreyHack.programPath": ["programPath", "program_path"],
	"GreyHack.resetCtfPassword": ["resetCtfPassword", "reset_ctf_password"],
	"GreyHack.getType": ["getType", "typeof"],
	"GreyHack.isType": ["isType", "is_type"], // custom
	"GreyHack.userBankNumber": ["userBankNumber", "user_bank_number"],
	"GreyHack.userInput": ["userInput", "user_input"],
	"GreyHack.userMailAddress": ["userMailAddress", "user_mail_address"],
	// MetaLib
	"GreyHack.MetaLib.debugTools": ["debugTools", "debug_tools"],
	"GreyHack.MetaLib.isPatched": ["isPatched", "is_patched"],
	"GreyHack.MetaLib.libName": ["libName", "lib_name"],
	// MetaMail
	// Metaxploit
	"GreyHack.Metaxploit.netUse": ["netUse", "net_use"],
	"GreyHack.Metaxploit.rshellClient": ["rshellClient", "rshell_client"],
	"GreyHack.Metaxploit.rshellServer": ["rshellServer", "rshell_server"],
	"GreyHack.Metaxploit.scanAddress": ["scanAddress", "scan_address"],
	// NetSession
	"GreyHack.NetSession.dumpLib": ["dumpLib", "dump_lib"],
	"GreyHack.NetSession.floodConnection": ["floodConnection", "flood_connection"],
	"GreyHack.NetSession.getNumConnGateway": ["getNumConnGateway", "get_num_conn_gateway"],
	"GreyHack.NetSession.getNumPortforward": ["getNumPortforward", "get_num_portforward"],
	"GreyHack.NetSession.getNumUsers": ["getNumUsers", "get_num_users"],
	"GreyHack.NetSession.isAnyActiveUser": ["isAnyActiveUser", "is_any_active_user"],
	"GreyHack.NetSession.isRootActiveUser": ["isRootActiveUser", "is_root_active_user"],
	// Port
	"GreyHack.Port.getLanIp": ["getLanIp", "get_lan_ip"],
	"GreyHack.Port.isClosed": ["isClosed", "is_closed"],
	"GreyHack.Port.portNumber": ["portNumber", "port_number"],
	// Router
	"GreyHack.Router.bssidName": ["bssidName", "bssid_name"],
	"GreyHack.Router.devicePorts": ["devicePorts", "device_ports"],
	"GreyHack.Router.devicesLanIp": ["devicesLanIp", "devices_lan_ip"],
	"GreyHack.Router.essidName": ["essidName", "essid_name"],
	"GreyHack.Router.firewallRules": ["firewallRules", "firewall_rules"],
	"GreyHack.Router.kernelVersion": ["kernelVersion", "kernel_version"],
	"GreyHack.Router.localIp": ["localIp", "local_ip"],
	"GreyHack.Router.pingPort": ["pingPort", "ping_port"],
	"GreyHack.Router.portInfo": ["portInfo", "port_info"],
	"GreyHack.Router.publicIp": ["publicIp", "public_ip"],
	"GreyHack.Router.usedPorts": ["usedPorts", "used_ports"],
	// Service
	"GreyHack.Service.installService": ["installService", "install_service"],
	"GreyHack.Service.startService": ["startService", "start_service"],
	"GreyHack.Service.stopService": ["stopService", "stop_service"],
	// Shell
	"GreyHack.Shell.connectService": ["connectService", "connect_service"],
	"GreyHack.Shell.hostComputer": ["hostComputer", "host_computer"],
	"GreyHack.Shell.startTerminal": ["startTerminal", "start_terminal"],
	// SmartAppliance
	"GreyHack.SmartAppliance.overrideSettings": ["overrideSettings", "override_settings"],
	"GreyHack.SmartAppliance.setAlarm": ["setAlarm", "set_alarm"],
	// SubWallet
	"GreyHack.SubWallet.checkPassword": ["checkPassword", "check_password"],
	"GreyHack.SubWallet.getBalance": ["getBalance", "get_balance"],
	"GreyHack.SubWallet.getInfo": ["getInfo", "get_info"],
	"GreyHack.SubWallet.getUser": ["getUser", "get_user"],
	"GreyHack.SubWallet.lastTransaction": ["lastTransaction", "last_transaction"],
	"GreyHack.SubWallet.setInfo": ["setInfo", "set_info"],
	"GreyHack.SubWallet.walletUsername": ["walletUsername", "wallet_username"],
	// TrafficNet
	"GreyHack.TrafficNet.cameraLinkSystem": ["cameraLinkSystem", "camera_link_system"],
	"GreyHack.TrafficNet.getCredentialsInfo": ["getCredentialsInfo", "get_credentials_info"],
	"GreyHack.TrafficNet.locateVehicle": ["locateVehicle", "locate_vehicle"],
	// Wallet
	"GreyHack.Wallet.buyCoin": ["buyCoin", "buy_coin"],
	"GreyHack.Wallet.cancelPendingTrade": ["cancelPendingTrade", "cancel_pending_trade"],
	"GreyHack.Wallet.getBalance": ["getBalance", "get_balance"],
	"GreyHack.Wallet.getGlobalOffers": ["getGlobalOffers", "get_global_offers"],
	"GreyHack.Wallet.getPendingTrade": ["getPendingTrade", "get_pending_trade"],
	"GreyHack.Wallet.getPin": ["getPin", "get_pin"],
	"GreyHack.Wallet.listCoins": ["listCoins", "list_coins"],
	"GreyHack.Wallet.listGlobalCoins": ["listGlobalCoins", "list_global_coins"],
	"GreyHack.Wallet.resetPassword": ["resetPassword", "reset_password"],
	"GreyHack.Wallet.sellCoin": ["sellCoin", "sell_coin"],
	"GreyHack.Wallet.showNodes": ["showNodes", "show_nodes"],
	// string
	"String.isMatch": ["isMatch", "is_match"],
	"String.toInt": ["toInt", "to_int"],
	"String.length": ["length", "len"],
	// Object
	"Object.size": ["size", "len"],
	// Array
	"Array.length": ["length", "len"],
} as const;